// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Disabled
  public void loginandvisitallshareslisting() {
    driver.get("https://www.moneyweb.co.za/");
    driver.manage().window().setSize(new Dimension(1728, 1001));
    driver.findElement(By.xpath("//span[contains(.,\'SIGN IN\')]")).click();
    driver.findElement(By.id("user_login")).click();
    driver.findElement(By.id("user_login")).sendKeys("inv_me_22");
    driver.findElement(By.id("user_pass")).sendKeys("Moss1234");
    driver.findElement(By.id("wp-submit")).click();
    driver.findElement(By.xpath("//div[@id=\'mobile-top-header-data\']/div[2]/a/span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-lg-6:nth-child(9) > .tools-under-menu a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".col-lg-6:nth-child(9) > .tools-under-menu a")).click();
    driver.findElement(By.cssSelector(".loggedOutHeight")).click();
  }
}
